[package]
name = "early-bird"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
winapi = { version = "0.3", features = ["processthreadsapi", "memoryapi", "winnt", "handleapi"] }
log = "0.4"
